spring:
  kafka:
    topic:
      transactions: "transaction"
    consumer:
      auto-offset-reset: earliest
      group-id: midas
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 33400

general:
  kafka-topic: "transaction"
  incentive-api-url: "http://localhost:8080/incentive"